2020-08-05 11:43:09,596 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 12:37:06,997 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 13:00:21,301 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 13:39:10,135 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 14:16:43,162 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 14:33:31,463 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 14:39:20,885 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 15:03:57,091 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 17:11:55,378 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 17:12:54,466 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 22:49:13,645 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 22:50:07,298 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
2020-08-05 22:52:15,497 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
2020-08-05 23:11:59,309 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-05 23:13:59,697 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
2020-08-05 23:19:04,429 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-08-30 20:46:26,919 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-04 11:12:37,816 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-04 12:17:48,453 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-05 14:49:06,204 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-05 15:05:37,081 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-05 15:09:58,879 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-05 15:25:29,542 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-05 16:35:04,558 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-06 07:37:35,819 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-06 08:27:04,283 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
2020-09-06 08:41:50,766 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
2020-09-06 09:07:35,621 INFO: Ogahslab startup [in /root/ogahslab/app/__init__.py:113]
2020-09-06 09:08:46,953 ERROR: Exception on /auth/reset_password_request [POST] [in /root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable
